SCREEN_WIDTH = 200
SCREEN_HEIGHT = 200

AGENT_SIZE = 1

PREY_BIRTH_RATE = 0.17
PREY_MAX_AGE = 6

HUNTER_ENERGY_TO_REPRODUCE = 30
HUNTER_MAX_AGE = 25
HUNTER_ENERGY_PER_PREY_EATEN = 50
HUNTER_START_ENERGY = 25

START_AMOUNT_HUNTERS = 20
START_AMOUNT_PREYS = 100

PYGAME_SCALE = 4
